### PR TITLE
Cakephp3 header format (adopted to coding standards)

### PR DESCRIPTION
**Pull request by klickagent**
Cakephp3 accepts header in different notation than the oAuth2 package (league/oauth2-server).
HTTP/1.1 400 Bad Request
should be
HTTP/1.1 400: Bad Request
in Cakephp3 in order not to cause an error in the header method of Network/Respone.

### CODE REVIEW

**Comment by dakota** [comment]
Still not passing coding standards (https://travis-ci.org/uafrica/oauth-server/jobs/71761068)

You don't need to create a new PR, just push the new commits to your branch and Github will keep the PR up-to-date.

**Comment by klickagent** [comment]
I never worked with Travis CI, where exactly do I find the coding conventions?

**Comment by dakota** [comment]
Here are the latest coding standard failures: https://travis-ci.org/uafrica/oauth-server/jobs/71776251#L239

This plugin follows the PSR-2 standard.

**Comment by klickagent** [comment]
Thanks for your help. I finally managed it to make the code following all conventions ;)

**Comment by dakota** [comment]
Implemented in https://github.com/uafrica/oauth-server/commit/efe4c0a4b5b9645cb9a2a57e561d4303c0364bee

Thanks for the fix! :100:

**Pull request closed without merging**
